let prod_combos = [
    {
        id: 1,
        acordion: "One",
        nombre: "Combo Emma",
        detalle: "Mesa Emma + 4 sillas capri",
        descripcion: "Mesa con tapa de melamina y color de caños (a eleccion). Sillas Capri tapizadas con Ecocuero o Chenille (a eleccion)",
        color:"Disponibles en varios colores",
        medidas: "0.90mts de diámetro",
        precio: 22000,
        img: "./img/Combo Emma/Combo Emma.png",
    },
    {
        id: 2,
        acordion: "Two",
        nombre: "Combo Toledo I",
        detalle: "Mesa toledo + 4 sillas capri",
        descripcion: "Mesa con tapa de melamina y color de caños (a eleccion). Sillas Capri tapizadas con Ecocuero o Chenille (a eleccion)",
        color:"Disponibles en varios colores",
        medidas: "1.20 x 0.60mts",
        precio: 22000,
        img: "./img/Combo Toledo/Combo Toledo.png",
    },
    {
        id: 3,
        acordion: "Three",
        nombre: "Combo Toledo II",
        detalle: "Mesa toledo + 6 sillas capri",
        descripcion: "Mesa con tapa de melamina y color de caños (a eleccion). Sillas Capri tapizadas con Ecocuero o Chenille (a eleccion)",
        color:"Disponibles en varios colores",
        medidas: "1.40 x 0.80mts",
        precio: 31200,
        img: "./img/Combo Toledo/Combo Toledo 6x.png",
    },
    {
        id: 4,
        acordion: "Four",
        nombre: "Combo Bari",
        detalle: "Mesa Terra + 4 sillas Bari",
        descripcion: "Mesa con tapa de melamina y color de caños (a eleccion). Sillas Capri tapizadas con Ecocuero o Chenille (a eleccion)",
        color:"Disponibles en varios colores",
        medidas: "1.20 x 0.80mts",
        precio: 27000,
        img: "./img/Combo Bari/Combo Bari.jpeg",
    },
    {
        id: 5,
        acordion: "Five",
        nombre: "Combo Burbuja",
        detalle: "Mesa Burbuja + 4 sillas burbuja",
        descripcion: "Mesa con tapa de melamina y color de caños (a eleccion). Sillas Capri tapizadas con Ecocuero o Chenille (a eleccion)",
        color:"Disponibles en varios colores",
        medidas: "0.90mts de diámetro",
        precio: 27000,
        img: "./img/Combo Burbuja/Combo-burbujax4.png",
    },
    {
        id: 6,
        acordion: "Six",
        nombre: "Combo Palermo",
        detalle: "Mesa Palermo + 6 sillas palermo",
        descripcion: "Mesa con tapa de melamina y color de caños (a eleccion). Sillas Capri tapizadas con Ecocuero o Chenille (a eleccion)",
        color:"Disponibles en varios colores",
        medidas: "1.50 x 0.80mts",
        precio: 35000,
        img: "./img/Combo Palermo/Combo-palermo-x6-naranja.jpeg",
    },
    {
        id: 7,
        acordion: "Seven",
        nombre: "Combo Escritorio I",
        detalle: "Escritorio Juvenil + 1 silla Sofía",
        descripcion: "Mesa con tapa de melamina y color de caños (a eleccion). Sillas Capri tapizadas con Ecocuero o Chenille (a eleccion)",
        color:"Disponibles en varios colores",
        medidas: "1.00 x 0.50 x 0.75mts",
        precio: 13200,
        img: "./img/Combo Escritorios/Combo Escritorio + silla Sofia.png",
    },
    {
        id: 8,
        acordion: "Eight",
        nombre: "Combo Emma",
        detalle: "Mesa Emma + 4 sillas capri",
        descripcion: "Mesa con tapa de melamina y color de caños (a eleccion). Sillas Capri tapizadas con Ecocuero o Chenille (a eleccion)",
        color:"Disponibles en varios colores",
        medidas: "0.90mts de diámetro",
        precio: 22000,
        img: "Combo Emma.png",
    }
];

for ( productos of prod_combos) {
    let containerProd = document.getElementById("productos__container");
    
}